# Generated by Django 5.2.17 on 2026-10-05 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Số thứ tự trong bộ 600 câu.', unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='questions/')),
                ('image_type', models.CharField(blank=True, choices=[('sign', 'Biển báo'), ('scenario', 'Sa hình / tình huống'), ('diagram', 'Hình minh hoạ')], max_length=16)),
                ('is_critical', models.BooleanField(db_index=True, default=False, help_text='Câu điểm liệt.')),
                ('source_page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions.chapter')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question')),
            ],
            options={
                'ordering': ['question', 'position'],
                'constraints': [models.UniqueConstraint(fields=('question', 'position'), name='unique_option_position'), models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='one_correct_option_per_question')],
            },
        ),
    ]
