# Generated by Django 5.2.17 on 2026-10-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='in_set_a',
            field=models.BooleanField(db_index=True, default=False, help_text='Thuộc bộ 250 câu hạng A1, A.'),
        ),
        migrations.AddField(
            model_name='question',
            name='in_set_b1',
            field=models.BooleanField(db_index=True, default=False, help_text='Thuộc bộ 300 câu hạng B1.'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_critical_a',
            field=models.BooleanField(default=False, help_text='Câu điểm liệt trong đề hạng A1, A.'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_critical_b1',
            field=models.BooleanField(default=False, help_text='Câu điểm liệt trong đề hạng B1.'),
        ),
    ]
