# Generated by Django 5.2.17 on 2026-10-05 15:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0002_question_in_set_a_question_in_set_b1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_class', models.CharField(choices=[('A1', 'A1'), ('A', 'A'), ('B1', 'B1'), ('B', 'B'), ('C1', 'C1'), ('C', 'C'), ('D1', 'D1'), ('D2', 'D2'), ('D', 'D'), ('BE', 'BE'), ('C1E', 'C1E'), ('CE', 'CE'), ('D1E', 'D1E'), ('D2E', 'D2E'), ('DE', 'DE')], max_length=4)),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('pass_score', models.PositiveSmallIntegerField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('in_progress', 'Đang làm'), ('submitted', 'Đã nộp')], default='in_progress', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('failed_critical', models.BooleanField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('is_critical', models.BooleanField(default=False)),
                ('selected_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exams.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='questions.question')),
            ],
            options={
                'ordering': ['attempt', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['user', '-started_at'], name='exams_exama_user_id_734ebb_idx'),
        ),
        migrations.AddConstraint(
            model_name='examitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'order'), name='unique_exam_item_order'),
        ),
        migrations.AddConstraint(
            model_name='examitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_exam_item_question'),
        ),
    ]
